### ISSUE TITLE
Blockchain parser downloading peercoin database even after changing conf.lisp file to other daemon server

### ISSUE THREAD

**Issue by ghost** [glv2/peercoin-blockchain-parser#1]
I have changed below conf.lisp file to get blockchain data from other server :

(defparameter *rpc-server-url* "customUrl")
(defparameter *rpc-username* "username")
(defparameter *rpc-password* "password")

(defparameter *rdbms-driver* :postgres)
(defparameter *rdbms-database* "peercoin")
(defparameter *rdbms-username* "username")
(defparameter *rdbms-password* "password")

But still i am gettting top addresses of peercoin (that start with character 'P')
Could anyone help for this !
Thanks in advance.

**Comment by glv2** [comment]
I don't understand your question.
Do you have problems updating the database using data from a RPC server?
Or do you have problems making requests to the database?
Or something else?

**Comment by ghost** [comment]
Hi @glv2 
I am able to update database successfully from peercoin server but i have created my own currency and running server for that, created private blockchain. I want to parse that blockchain instead of peercoin blockchain.
When i am running this parser code for my blockchain and updating database, it is giving addresses of peercoin blockchain.
(I have changed conf.lisp file and magic id according to my server)
Thanks in advance
Please help in this regard.

**Comment by glv2** [comment]
For a custom blockchain, I think you would need to change ```+peercoin-magic-id+``` and ```+peercoin-testnet-magic-id+``` in *file.lisp*, as well as ```+peercoin-version-byte+``` and ```+peercoin-testnet-version-byte+``` in *utils.lisp*.

**Comment by ghost** [comment]
Thanks, now its working.
